-- =============================================================================
-- Migration 007 — Risk & Anomaly Detection Domain
-- Tables: risk_assessments, anomaly_results
-- =============================================================================

-- ── risk_assessments ──────────────────────────────────────────────────────────
-- Per-bid risk profile generated by the AI pipeline.
-- Multiple risk flags can exist per bid (one row per risk category per bid).
-- Aggregated risk level determines if a bid needs additional scrutiny.
CREATE TABLE IF NOT EXISTS risk_assessments (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  bid_id            UUID          NOT NULL REFERENCES bids(id) ON DELETE CASCADE,
  evaluation_id     UUID          REFERENCES ai_evaluations(id) ON DELETE SET NULL,
  assessed_by       UUID          REFERENCES users(id),  -- NULL = automated
  risk_category     risk_category NOT NULL,
  risk_level        risk_level    NOT NULL,
  title             VARCHAR(300)  NOT NULL,
  description       TEXT          NOT NULL,
  evidence          JSONB         NOT NULL DEFAULT '{}',  -- supporting data
  mitigation_notes  TEXT,
  is_resolved       BOOLEAN       NOT NULL DEFAULT FALSE,
  resolved_by       UUID          REFERENCES users(id),
  resolved_at       TIMESTAMPTZ,
  resolution_notes  TEXT,
  metadata          JSONB         NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE risk_assessments IS 'Risk flags per bid per category. Multiple risks can exist per bid.';
COMMENT ON COLUMN risk_assessments.evidence IS 'Supporting evidence JSON: {source, excerpt, confidence, data_points[]}';
COMMENT ON COLUMN risk_assessments.is_resolved IS 'Set to TRUE when a human officer reviews and dismisses or addresses the risk.';

-- ── anomaly_results ───────────────────────────────────────────────────────────
-- Cross-bid anomaly detection results. Anomalies are tender-level, not bid-level.
-- Detected by comparing bids ACROSS the tender (collusion, clustering, etc.)
-- May reference multiple bids via the `affected_bid_ids` array.
CREATE TABLE IF NOT EXISTS anomaly_results (
  id                UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
  tender_id         UUID              NOT NULL REFERENCES tenders(id) ON DELETE CASCADE,
  evaluation_id     UUID              REFERENCES ai_evaluations(id) ON DELETE SET NULL,
  detected_by       UUID              REFERENCES users(id),  -- NULL = automated
  anomaly_type      anomaly_type      NOT NULL,
  severity          anomaly_severity  NOT NULL,
  title             VARCHAR(300)      NOT NULL,
  description       TEXT              NOT NULL,
  affected_bid_ids  UUID[]            NOT NULL DEFAULT '{}',  -- bids involved
  detection_data    JSONB             NOT NULL DEFAULT '{}',  -- raw detection evidence
  confidence_score  NUMERIC(4, 3),                            -- 0.000–1.000
  is_confirmed      BOOLEAN,                                  -- NULL = pending review
  reviewed_by       UUID              REFERENCES users(id),
  reviewed_at       TIMESTAMPTZ,
  review_notes      TEXT,
  escalated_to      UUID              REFERENCES users(id),   -- if escalated
  escalated_at      TIMESTAMPTZ,
  metadata          JSONB             NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ       NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_anomaly_confidence
    CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1))
);

COMMENT ON TABLE anomaly_results IS 'Cross-bid anomaly detection results at tender level. NULL is_confirmed = pending human review.';
COMMENT ON COLUMN anomaly_results.affected_bid_ids IS 'Array of bid UUIDs involved in the anomaly. Used for cross-referencing without FK overhead.';
COMMENT ON COLUMN anomaly_results.is_confirmed IS 'NULL = not yet reviewed. TRUE = confirmed anomaly. FALSE = dismissed false positive.';
